# Generated by Django 2.0.2 on 2018-02-11 16:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default=None, max_length=32, null=True)),
                ('description', models.TextField(blank=True, default=None, max_length=1024)),
                ('avatar', models.ImageField(null=True, upload_to='static/media/events_gallery/admins')),
            ],
            options={
                'verbose_name': 'Org',
                'verbose_name_plural': 'Orgs',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default=None, max_length=32, null=True)),
                ('name', models.CharField(default=None, max_length=32, null=True)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+38 073 000 33 00'.", regex='^\\+?380?\\d{9}$')])),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='org',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.User'),
        ),
    ]
