# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='avatar',
            field=models.ImageField(null=True, upload_to=b'static/media/events_gallery/args'),
        ),
    ]
