# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20180506_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='avatar',
            field=models.ImageField(null=True, upload_to=b'sharks-blog/static/media/events_gallery/orgs'),
        ),
    ]
