# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20180501_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(null=True, upload_to=b'sharks-blog/static/media/events_gallery/posters'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to=b'sharks-blog/static/media/events_gallery/gallery'),
        ),
    ]
