<<<<<<< HEAD
# Generated by Django 2.0.2 on 2018-02-11 16:51
=======
# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 19:52
from __future__ import unicode_literals
>>>>>>> 416b42aab500af35c8af310b942f535a8ddf82fe

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0001_initial'),
<<<<<<< HEAD
        ('event', '0001_initial'),
=======
        ('event', '0004_auto_20180501_1047'),
>>>>>>> 416b42aab500af35c8af310b942f535a8ddf82fe
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1.0)),
<<<<<<< HEAD
                ('price', models.IntegerField(blank=True)),
                ('sum', models.IntegerField()),
=======
                ('sum', models.IntegerField(blank=True)),
>>>>>>> 416b42aab500af35c8af310b942f535a8ddf82fe
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.User')),
            ],
            options={
<<<<<<< HEAD
                'verbose_name_plural': 'Orders',
                'verbose_name': 'Order',
=======
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
>>>>>>> 416b42aab500af35c8af310b942f535a8ddf82fe
            },
        ),
    ]
