# Generated by Django 2.0.2 on 2018-02-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.IntegerField(blank=True),
        ),
    ]
